name: Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: ['3.3', '3.4', '4.0']
        rails: ['72', '80', '81', 'main']
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run StandardRb linting
        run: bundle exec standardrb
      - name: Run specs
        run: bundle exec rspec spec

  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint GitHub Actions workflows
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          advanced-security: false
