name: Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: ['3.3', '3.4', '4.0']
        rails: ['72', '80', '81', 'main']
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run StandardRb linting
        run: bundle exec standardrb
      - name: Run specs
        run: bundle exec rspec spec

  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Lint GitHub Actions workflows
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          advanced-security: false
