name: Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: ['3.3', '3.4', '4.0']
        rails: ['72', '80', '81', 'main']
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run StandardRb linting
        run: bundle exec standardrb
      - name: Run specs
        run: bundle exec rspec spec

  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Lint GitHub Actions workflows
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: false
